# Site settings
title: Blognote
header-img: img/home-bg.jpg
email: vromanik@yandex.ru
description: "Blognote!"
baseurl: ""
url: "http://blognote.github.com"
twitter_username: SBootstrap
github_username:  blognote
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
