# Site settings
title: Blognote
header-img: img/home-bg.jpg
email: metotas@yourdomain.com
copyright_name: 
description: "Blognote!"
baseurl: ""
url: "http://blognote.github.com"
twitter_username: SBootstrap
github_username:  blognote
#facebook_username:  IronSummitMedia
email_username:  metotas@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
